version: "3"

services:
  db:
    container_name: maria_mt_section
    image: mariadb:10.7.8
    volumes:
      - ../db/data/:/var/lib/mysql/
      - ../db/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: $TIME_ZONE
    ports:
      - $MYSQL_PORT:$MYSQL_DOCKER_PORT
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    entrypoint: redis-server --requirepass $REDIS_PASS --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - default
    ports:
      - $REDIS_PORT:$REDIS_DOCKER_PORT
    restart: unless-stopped
  
